[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-scripts/wombat256.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['iceberg.vim']
hook_add = 'source ~/.vim/rc/plugins/lightline.rc.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_map_keys = 0
nmap [g <Plug>GitGutterPrevHunk
nmap ]g <Plug>GitGutterNextHunk
'''

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
    nmap s <Nop>
    xmap s <Nop>
'''

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
    set helplang=ja,en
'''

[[plugins]]
repo = 'urbainvaes/vim-remembrall'
hook_add = '''
" Show ',' normal mode mappings when key ',' is pressed
nnoremap <silent> , :call remembrall#remind('n', ',')<cr>
" Show ',' normal mode mappings when the key combination ',?' is pressed,
" so we don't have to wait for the timeout.
nnoremap <silent> ,? :call remembrall#remind('n', ',')<cr>
" Show visual mode mappings
vnoremap <silent> ? :call remembrall#remind('n', '')<cr>
'''

