[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-scripts/wombat256.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['iceberg.vim']
hook_add = 'source ~/.vim/rc/plugins/lightline.rc.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:loaded_indentLine = 1
'''

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
    nmap s <Nop>
    xmap s <Nop>
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
    set helplang=ja,en
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
