[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
build = ':UpdateRemotePlugins'
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
on_cmd = 'Denite'
depends = ['neomru.vim', 'neoinclude.vim']
build = ':UpdateRemotePlugins'
hook_source = 'source ~/.vim/rc/plugins/denite.rc.vim'
hook_add = '''
    " Prefix key
    nmap [denite] <Nop>
    map <C-j> [denite]

    " Keymap
    " Current direcotry files
    nmap <silent> [denite]<C-p> :<C-u>Denite file_rec -highlight-mode-insert=Search<CR>
    " Buffer files
    nmap <silent> [denite]<C-b> :<C-u>Denite buffer -highlight-mode-insert=Search<CR>
    " Outline current file
    nmap <silent> [denite]<C-o> :<C-u>Denite outline -highlight-mode-insert=Search<CR>
    " Reccent file
    nmap <silent> [denite]<C-r> :<C-u>Denite file_mru -highlight-mode-insert=Search<CR>
    " Help tag
    nmap <silent> [denite]<C-h> :<C-u>Denite help -highlight-mode-insert=Search<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
