[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'michalbachowski/vim-wombat256mod'

# [[plugins]]
# repo = 'vim-airline/vim-airline'
# depends = ['vim-airline-themes']
# hook_add = '''
#     source ~/.vim/rc/plugins/airline.rc.vim
# '''
#
# [[plugins]]
# repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:loaded_indentLine = 1
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
    set helplang=ja,en
'''
