[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
on_cmd = 'Denite'
depends = ['neomru.vim', 'neoinclude.vim']
hook_source = 'source ~/.vim/rc/plugins/denite.rc.vim'
hook_add = '''
    " Prefix key
    nmap [denite] <Nop>
    map <C-j> [denite]

    " Keymap
    " Current direcotry files
    nmap <silent> [denite]<C-P> :<C-u>Denite file_rec -highlight-mode-insert=Search<CR>
    " Buffer files
    nmap <silent> [denite]<C-B> :<C-u>Denite buffer -highlight-mode-insert=Search<CR>
    " Outline current file
    nmap <silent> [denite]<C-O> :<C-u>Denite outline -highlight-mode-insert=Search<CR>
    " Ctag simbol
    nmap <silent> [denite]<C-]> :<C-u>Denite tag -highlight-mode-insert=Search<CR>
    " Reccent file
    nmap <silent> [denite]<C-r> :<C-u>Denite file_mru -highlight-mode-insert=Search<CR>
    " Command history
    nmap <silent> [denite]<C-H> :<C-u>Denite command_history -highlight-mode-insert=Search<CR>
    " Seach dotfiles
    nmap <silent> [denite]<C-V> :<C-u>call denite#start([{'name': 'file_rec', 'args': ['~/.dotfiles']}]) -highlight-mode-insert=Search=Search<CR>
    " Definetion of class/function
    nmap <silent> [denite]<C-D> :Denite -buffer-name=gtags_completion gtags_completion -highlight-mode-insert=Search<cr>
    " Change directory to Repository of the ghq
    nmap <silent> [denite]<C-G> :<C-u>Denite ghq -default-action=cd -highlight-mode-insert=Search<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
