
[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "!has('nvim')"
on_i = 1
hook_source = '''
    let g:neocomplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python']

[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = ['python', "djangohtml"]

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
on_ft = ['python']

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['vimproc.vim', 'shabadou.vim']
on_ft = ['python']
hook_source = '''
  source ~/.vim/rc/plugins/vimquickrun.rc.vim
'''

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
hook_source = '''
call quickrun#module#register(shabadou#make_quickrun_hook_anim(
    \ "v_cannon",
    \ [
        \ '|        ベクターキャノンモードヘ移行        |',
        \ '||        エネルギーライン、全段直結        ||',
        \ '|||   ランディングギア、アイゼン、ロック   |||',
        \ '||||       チャンバー内、正常加圧中       ||||',
        \ '|||||        ライフリング回転開始        |||||',
        \ '||||||             撃てます             ||||||',
    \ ],
    \ 5,
    \), 1)
'''

[[plugins]]
repo = 'neomake/neomake'
if = "has('nvim')"
depends = ['vimproc.vim']
on_ft = ['python']
hook_source = '''
    autocmd! BufEnter,BufWritePost * Neomake
    let g:neomake_python_enabled_makers = ['python', 'flake8']
'''

