
[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "!has('nvim')"
on_i = 1
hook_source = '''
    let g:neocomplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python', "python3"]
# hook_source = '''
#     let g:deoplete#enable_profile = 1
#     let g:deoplete#sources#jedi#debug_server = 1
#     call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
#     call deoplete#custom#set('jedi', 'debug_enabled', 1)
# '''

[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = ['python', "python3", "djangohtml"]

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
on_ft = ['python', "python3"]

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python', "python3"]
