[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "!has('nvim')"
on_i = 1
hook_source = '''
    let g:neocomplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/unite.vim'
if = "!has('nvim')"
on_cmd = 'Unite'
depends = ['neomru.vim']
hook_source = 'source ~/.vim/rc/plugins/unite.rc.vim'
hook_add = '''
    " Prefix key
    nnoremap [unite] <Nop>
    nmap <Space>u [unite]

    " Keymap
    " Current direcotry files
    nnoremap <silent> [unite]<C-p> :<C-u>Unite<Space>file_rec/async:!<CR>
    " Buffer files
    nnoremap <silent> [unite]<C-b> :<C-u>Unite buffer<CR>
    " Grep files
    nnoremap <silent> [unite]<C-g> :<C-u>Unite<Space>grep -buffer-name=search -auto-preview -no-quit -no-empty -resume<CR>
    " Recent files
    nnoremap <silent> [unite]<C-r> :<C-u>Unite file_mru buffer<CR>
    " Yank history
    nnoremap <silent> [unite]<C-y> :<C-u>Unite history/yank<CR>
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
on_cmd = 'Denite'
depends = ['neomru.vim']
hook_source = 'source ~/.vim/rc/plugins/denite.rc.vim'
hook_add = '''
    " Prefix key
    nnoremap [denite] <Nop>
    nmap <C-j> [denite]

    " Keymap
    " Current direcotry files
    nnoremap <silent> [denite]<C-p> :<C-u>Denite file_rec<CR>
    " Buffer files
    nnoremap <silent> [denite]<C-b> :<C-u>Denite buffer<CR>
    " Grep files
    nnoremap <silent> [denite]<C-g> :<C-u>Denite -auto_preview grep<CR>
    " Grep cursor word
    nnoremap <silent> [denite]<C-]> :<C-u>DeniteCursorWord grep<CR>
    " Recent files
    nnoremap <silent> [denite]<C-r> :<C-u>Denite file_mru<CR>
    " Outline
    nnoremap <silent> [denite]<C-o> :<C-u>Denite outline<CR>
    " Command history
    nnoremap <silent> [denite]<C-n> :<C-u>Denite command_history<CR>
    " Seach dotfiles
    nnoremap <silent> [denite]<C-v> :<C-u>call denite#start([{'name': 'file_rec', 'args': ['~/.dotfiles']}])<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python']

[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = ['python', "djangohtml"]

# [[plugins]]
# repo = 'lambdalisue/vim-pyenv'
# on_ft = ['python']

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['vimproc.vim', 'shabadou.vim']
on_ft = ['python']
hook_source = '''
  source ~/.vim/rc/plugins/vimquickrun.rc.vim
'''

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
hook_source = '''
call quickrun#module#register(shabadou#make_quickrun_hook_anim(
    \ "v_cannon",
    \ [
        \ '|        ベクターキャノンモードヘ移行        |',
        \ '||        エネルギーライン、全段直結        ||',
        \ '|||   ランディングギア、アイゼン、ロック   |||',
        \ '||||       チャンバー内、正常加圧中       ||||',
        \ '|||||        ライフリング回転開始        |||||',
        \ '||||||             撃てます             ||||||',
    \ ],
    \ 5,
    \), 1)
'''

[[plugins]]
repo = 'neomake/neomake'
if = "has('nvim')"
depends = ['vimproc.vim']
on_ft = ['python']
hook_source = '''
    autocmd! BufEnter,BufWritePost * Neomake
    let g:neomake_python_enabled_makers = ['python', 'flake8']
'''

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = ['go']
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#go#align_class = 1
    let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
    let g:deoplete#sources#go#package_dot = 1
    let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

