[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
    set background=dark
'''

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'michalbachowski/vim-wombat256mod'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
    source ~/.vim/rc/plugins/airline.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
    " Add comment to beginning line(consider whitespace)
    nmap <Leader>c <Plug>(caw:hatpos:toggle)
    vmap <Leader>c <Plug>(caw:hatpos:toggle)
    " Add comment to beginning line(ignore whitespace)
    nmap <Leader>, <Plug>(caw:zeropos:toggle)
    vmap <Leader>, <Plug>(caw:zeropos:toggle)
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <Space>f :<C-u>NERDTreeToggle<CR>
    let NERDTreeIgnore=['\.pyc$']
'''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
    nmap <Space>t :TagbarToggle<CR>
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
    nmap [figitive] <Nop>
    map <Leader>g [figitive]
    nmap <silent> [figitive]s :<C-u>Gstatus<CR>
    nmap <silent> [figitive]d :<C-u>Gdiff<CR>
    nmap <silent> [figitive]b :<C-u>Gblame<CR>
    nmap <silent> [figitive]l :<C-u>Glog<CR>
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['vim-fugitive']

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
    source ~/.vim/rc/plugins/openbrowser.rc.vim
'''

[[plugins]]
repo = 'mattn/benchvimrc-vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
    nnoremap <silent> <Leader>w :FixWhitespace<CR>
'''

[[plugins]]
repo = 'lambdalisue/vim-gista'
hook_add = '''
    let g:gista#client#default_username = 'lighttiger2505'
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:loaded_indentLine = 1
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = 'EasyAlign'
hook_add = '''
    vmap <Enter> <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'kana/vim-tabpagecd'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
    set helplang=ja,en
'''
