[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
    source ~/.vim/rc/plugins/unite.rc.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru']
hook_add = '''
    source ~/.vim/rc/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
hook_add = '''
    source ~/.vim/rc/plugins/neosnippet.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline_theme = 'badwolf'
    let g:airline#extensions#virtualenv#enabled = 1
    set laststatus=2
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
    source ~/.vim/rc/plugins/caw.rc.vim
'''

[[plugins]]
repo = 'neomake/neomake'
if = "has('nvim')"
hook_add = '''
    autocmd! BufEnter,BufWritePost * Neomake
    let g:neomake_python_enabled_makers = ['python', 'flake8']
'''

[[plugins]]
repo = 'vim-syntastic/syntastic'
if = "!has('nvim')"
hook_add = '''
    source ~/.vim/rc/plugins/syntastic.rc.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <Space>ff :<C-u>NERDTreeToggle<CR>
    let NERDTreeIgnore = ['\.pyc$']
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['vimproc.vim']
hook_add = '''
  source ~/.vim/rc/plugins/vimquickrun.rc.vim
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
    source ~/.vim/rc/plugins/openbrowser.rc.vim
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
    set background=dark
'''

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'nanotech/jellybeans.vim'
