
[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  source ~/.vim/rc/plugins/vimquickrun.rc.vim
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  source ~/.vim/rc/plugins/openbrowser.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
