[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python']
hook_source = '''
    call deoplete#custom#set('jedi', 'rank', 5)
'''


[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = ['python', 'djangohtml']

# [[plugins]]
# repo = 'lambdalisue/vim-pyenv'
# on_ft = ['python']

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
on_ft = ['python']
repo = 'aliev/vim-compiler-python'
