
[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "!has('nvim')"
on_i = 1
hook_source = '''
    let g:neocomplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python', "python3", "djangohtml"]

# [[plugins]]
# repo = 'davidhalter/jedi-vim'
# on_ft = ['python', "python3", "djangohtml"]
# hook_source = '''
#     let g:jedi#completions_enabled = 0
#     let g:jedi#auto_vim_configuration = 0
#     let g:jedi#smart_auto_mappings = 1
#     let g:jedi#show_call_signatures = 0
#     let g:jedi#rename_command = '<Leader>R'
# '''

[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = ['python', "python3", "djangohtml"]

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
on_ft = ['python', "python3", "djangohtml"]

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python', "python3", "djangohtml"]
hook_source = '''
    let g:virtualenv_directory = '~/.virtualenvs'
'''
