[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
    set background=dark
'''

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'michalbachowski/vim-wombat256mod'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
    let g:airline#extensions#ale#error_symbol = '⨉'
    let g:airline#extensions#ale#warning_symbol = '⚠'

    " Mode shortening
    let g:airline_mode_map = {
        \ '__' : '-',
        \ 'n'  : 'N',
        \ 'i'  : 'I',
        \ 'R'  : 'R',
        \ 'c'  : 'C',
        \ 'v'  : 'V',
        \ 'V'  : 'V',
        \ '' : 'V',
        \ 's'  : 'S',
        \ 'S'  : 'S',
        \ '' : 'S',
        \ }
    " Appearance
    let g:airline_powerline_fonts = 1
    let g:airline_theme = 'badwolf'

    " Disable git hunks
    let g:airline#extensions#hunks#enabled = 0

    " Enable virtualenv name
    let g:airline#extensions#virtualenv#enabled = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
    " Add comment to beginning line(consider whitespace)
    nmap <Leader>c <Plug>(caw:hatpos:toggle)
    vmap <Leader>c <Plug>(caw:hatpos:toggle)
    " Add comment to beginning line(ignore whitespace)
    nmap <Leader>, <Plug>(caw:zeropos:toggle)
    vmap <Leader>, <Plug>(caw:zeropos:toggle)
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <Space>f :<C-u>NERDTreeToggle<CR>
    let NERDTreeIgnore = ['\.pyc$']
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
    nnoremap [figitive] <Nop>
    nnoremap <Leader>g [figitive]
    nnoremap <silent> [figitive]s :<C-u>Gstatus<CR>
    nnoremap <silent> [figitive]d :<C-u>Gdiff<CR>
    nnoremap <silent> [figitive]b :<C-u>Gblame<CR>
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['vim-fugitive']

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'mattn/benchvimrc-vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
    nnoremap <silent> <Leader>w :FixWhitespace<CR>
'''

[[plugins]]
repo = 'lambdalisue/vim-gista'
hook_add = '''
    let g:gista#client#default_username = 'lighttiger2505'
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = 'EasyAlign'
hook_add = '''
    vmap <Enter> <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = '''
    " Options
    let g:Gtags_Auto_Map = 0
    let g:Gtags_OpenQuickfixWindow = 1
    " Keymap
    " Show definetion of function cousor word on quickfix
    nnoremap <silent> D :<C-u>exe("Gtags ".expand('<cword>'))<CR>
    " Show reference of cousor word on quickfix
    nnoremap <silent> S :<C-u>exe("Gtags -r ".expand('<cword>'))<CR>
'''
