
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
depends = ['badwolf']
hook_post_source = '''
    IndentGuidesEnable
'''

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  source ~/.vim/rc/plugins/vimquickrun.rc.vim
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  source ~/.vim/rc/plugins/openbrowser.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python', "python3", "djangohtml"]

[[plugins]]
repo = 'davidhalter/jedi-vim'
if = "!has('nvim')"
on_ft = ['python', "python3", "djangohtml"]
hook_source = '''
    let g:jedi#completions_enabled = 0
    let g:jedi#auto_vim_configuration = 0
    let g:jedi#smart_auto_mappings = 0
    let g:jedi#show_call_signatures = 0
'''

[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = ['python', "python3", "djangohtml"]

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
on_ft = ['python', "python3", "djangohtml"]

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python', "python3", "djangohtml"]
hook_source = '''
    let g:virtualenv_directory = '~/.virtualenvs'
'''
