[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
    set background=dark
'''

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'michalbachowski/vim-wombat256mod'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru']
hook_add = '''
    source ~/.vim/rc/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
hook_add = '''
    source ~/.vim/rc/plugins/neosnippet.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline_theme = 'badwolf'
    let g:airline#extensions#virtualenv#enabled = 1
    set laststatus=2
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
    source ~/.vim/rc/plugins/caw.rc.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <Space>f :<C-u>NERDTreeToggle<CR>
    let NERDTreeIgnore = ['\.pyc$']
'''

[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
    nnoremap [figitive] <Nop>
    nmap <Leader>g [figitive]

    nnoremap <silent> [figitive]a :<C-u>Git add -p<CR>
    nnoremap <silent> [figitive]c :<C-u>Git commit -m<Space>
    nnoremap <silent> [figitive]s :<C-u>Gstatus<CR>
    nnoremap <silent> [figitive]d :<C-u>Gdiff<CR>
    nnoremap <silent> [figitive]b :<C-u>Gblame<CR>
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['vim-fugitive']

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
    source ~/.vim/rc/plugins/openbrowser.rc.vim
'''

[[plugins]]
repo = 'mattn/benchvimrc-vim'

