[[plugins]]
repo = 'Shougo/dein.vim'

# [[plugins]]
# repo = 'Shougo/neocomplete.vim'
# if = "has('lua')"
# on_event = 'InsertEnter'
# hook_add = '''
#   let g:neocomplete#enable_at_startup = 1
#   source ~/.vim/rc/plugins/neocomplete.rc.vim
# '''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_event = 'InsertEnter'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
    source ~/.vim/rc/plugins/unite.rc.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru']
hook_add = '''
    source ~/.vim/rc/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make' 

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
hook_add = '''
    source ~/.vim/rc/plugins/neosnippet.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline_theme = 'badwolf'
    let g:airline#extensions#virtualenv#enabled = 1
    set laststatus=2
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
    source ~/.vim/rc/plugins/caw.rc.vim
'''

[[plugins]]
repo = 'neomake/neomake'
if = "has('nvim')"
hook_add = '''
    autocmd! BufEnter,BufWritePost * Neomake
    let g:neomake_python_enabled_makers = ['python', 'flake8']
'''

[[plugins]]
repo = 'vim-syntastic/syntastic'
if = "!has('nvim')"
hook_add = '''
    source ~/.vim/rc/plugins/syntastic.rc.vim
'''

[[plugins]]
<<<<<<< HEAD
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <Space>ff :<C-u>NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'sjl/badwolf'
=======
repo = 'thinca/vim-quickrun'
hook_add = '''
  source ~/.vim/rc/plugins/vimquickrun.rc.vim
'''
>>>>>>> origin/develop

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
    source ~/.vim/rc/plugins/openbrowser.rc.vim
'''

[[plugins]]
<<<<<<< HEAD
repo = 'w0ng/vim-hybrid'
hook_add = '''
    set background=dark
'''

=======
repo = 'sjl/badwolf'

[[plugins]]
repo = 'nanotech/jellybeans.vim'
>>>>>>> origin/develop
