[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_add = '''
  let g:neocomplete#enable_at_startup = 1
  source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
  source ~/.vim/rc/plugins/unite.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make' 

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
hook_add = '''
  source ~/.vim/rc/plugins/neosnippet.rc.vim
'''

# [[plugins]]
# repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  source ~/.vim/rc/plugins/vimairline.rc.vim
'''

# [[plugins]]
# repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Shougo/vimfiler'
hook_add = '''
  source ~/.vim/rc/plugins/vimfiler.rc.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  source ~/.vim/rc/plugins/caw.rc.vim
'''

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = '''
  source ~/.vim/rc/plugins/syntastic.rc.vim
'''

[[plugins]]
repo = 'sjl/badwolf'
