[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
on_cmd = 'Denite'
depends = ['neomru.vim']
hook_source = 'source ~/.vim/rc/plugins/denite.rc.vim'
hook_add = '''
    " Prefix key
    noremap [denite] <Nop>
    map <C-j> [denite]

    " Keymap
    " Current direcotry files
    nmap <silent> [denite]<C-p> :<C-u>Denite file_rec<CR>
    " Buffer files
    nmap <silent> [denite]<C-b> :<C-u>Denite buffer<CR>
    " Grep files
    nmap <silent> [denite]<C-s> :<C-u>Denite grep<CR>
    " Grep cursor word
    nmap <silent> [denite]<C-g> :<C-u>DeniteCursorWord grep<CR>
    " Recent files
    nmap <silent> [denite]<C-r> :<C-u>Denite file_mru<CR>
    " Outline
    nmap <silent> [denite]<C-o> :<C-u>Denite outline<CR>
    " Command history
    nmap <silent> [denite]<C-n> :<C-u>Denite command_history<CR>
    " Seach dotfiles
    nmap <silent> [denite]<C-v> :<C-u>call denite#start([{'name': 'file_rec', 'args': ['~/.dotfiles']}])<CR>
'''
