env:
  TERM: xterm-256color

dpi:
  x: 96.0
  y: 96.0

tabspaces: 8
draw_bold_text_with_bright_colors: true
render_timer: false

font:
  use_thin_strokes: true
  normal:
    family: Inconsolata-g for Powerline
    # style: Regular
  bold:
    family: Inconsolata-g for Powerline
    # style: Bold
  italic:
    family: Inconsolata-g for Powerline
    # style: Italic
  size: 14.0
  offset:
    x: 0.0
    y: 0.0

colors:
  primary:
    background: '0x191919'
    foreground: '0xdee2ea'
  normal:
    black:   '0x272c42'
    red:     '0xe27878'
    green:   '0xb4be82'
    yellow:  '0xe4aa80'
    blue:    '0x84a0c6'
    magenta: '0xa093c7'
    cyan:    '0x89b8c2'
    white:   '0x6b7089'
  bright:
    black:   '0x3d425b'
    red:     '0xe27878'
    green:   '0x07d774'
    yellow:  '0xb4be82'
    blue:    '0x84a0c6'
    magenta: '0xa093c7'
    cyan:    '0x89b8c2'
    white:   '0xc6c8d1'

visual_bell:
  duration: 0
